In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("processed_data.csv")

In [3]:
df.head()

,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,...,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9
0,1.0,1.789375,2.578750,3.368125,4.157500,4.946875,5.736250,6.525625,7.315000,8.104375,...,10.12,9.96,16.92,7.60,27.22,18.05,26.47,18.75,17.84,14.92
1,1.0,0.998632,0.997264,0.995896,0.994528,0.993160,0.991792,0.990424,0.989056,0.987688,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,1.0,1.013776,1.027551,1.041327,1.055103,1.068878,1.082654,1.096430,1.110205,1.123981,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,1.0,1.033438,1.066875,1.100313,1.133750,1.167188,1.200625,1.234062,1.267500,1.300938,...,6.50,9.99,11.78,18.59,26.80,18.57,14.59,12.82,19.37,15.92
4,1.0,2.900000,3.420000,3.810000,4.580000,3.560000,4.250000,3.860000,3.530000,3.410000,...,17.77,10.37,15.32,13.51,12.23,14.68,16.35,18.14,18.41,17.31

In [4]:
df.describe()

,FLAG,2014/1/1,2014/1/10,2014/1/11,2014/1/12,2014/1/13,2014/1/14,2014/1/15,2014/1/16,2014/1/17,...,2016/9/28,2016/9/29,2016/9/3,2016/9/30,2016/9/4,2016/9/5,2016/9/6,2016/9/7,2016/9/8,2016/9/9
count,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,...,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000,41166.000000
mean,0.079945,3.499766,3.277922,3.300310,3.533271,3.558026,3.634597,3.743064,3.666295,3.617965,...,6.576040,6.828638,7.799955,7.190622,8.174435,8.211920,8.283232,8.094089,7.772609,7.487487
std,0.271211,6.480684,6.464771,6.412743,6.283228,6.169396,6.355918,6.403347,6.309864,6.095689,...,8.889578,9.265953,10.697990,9.951603,11.046514,11.205901,11.191764,11.001072,10.633700,10.226071
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000274,0.001915,0.000000,0.001245,0.000000,0.000000,...,0.610000,0.770000,0.820000,0.820000,0.840000,0.870000,0.880000,0.860000,0.850000,0.850000
50%,0.000000,0.177344,0.250000,0.357187,0.545278,0.690000,0.681678,0.783125,0.710000,0.812813,...,4.240000,4.570000,4.880000,4.720000,5.030000,5.000000,5.070000,5.000000,4.910000,4.820000
75%,0.000000,4.860000,4.370000,4.440000,4.880000,4.990000,4.950000,5.180000,5.010000,5.130000,...,9.000000,9.157500,10.420000,9.480000,11.040000,11.040000,11.270000,10.960000,10.430000,9.990000
max,1.000000,183.390000,415.810000,461.480000,227.340000,85.330000,87.250000,87.600000,88.550000,86.760000,...,150.490000,151.840000,197.030000,175.910000,193.940000,193.320000,185.390000,265.610000,173.780000,179.600000

In [5]:
df['FLAG'].value_counts()

0.0    37875
1.0     3291
Name: FLAG, dtype: int64

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from imblearn.over_sampling import SMOTE

# Load the preprocessed DataFrame from the CSV file
df = pd.read_csv('processed_data.csv')

# Separate features (X) and target variable (y)
X = df.drop(columns=['FLAG'])
y = df['FLAG']

# Apply SMOTE to address class imbalance
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split the resampled data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Initialize SVM classifier with rbf kernel
svc = SVC(kernel='rbf')

# Fit the model to the training data
svc.fit(X_train, y_train)

# Predict using the trained model on the test data
y_pred = svc.predict(X_test)

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[6278 1257]
 [1664 5951]]

In [7]:
from sklearn.metrics import confusion_matrix, classification_report
# Compute classification report
report = classification_report(y_test, y_pred)

# Print classification report
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

         0.0       0.79      0.83      0.81      7535
         1.0       0.83      0.78      0.80      7615

    accuracy                           0.81     15150
   macro avg       0.81      0.81      0.81     15150
weighted avg       0.81      0.81      0.81     15150

In [8]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski')
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)

[[5389 2146]
 [  18 7597]]

In [9]:
# Compute classification report
report = classification_report(y_test, y_pred)

# Print classification report
print('Classification Report:')
print(report)

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.72      0.83      7535
         1.0       0.78      1.00      0.88      7615

    accuracy                           0.86     15150
   macro avg       0.89      0.86      0.85     15150
weighted avg       0.89      0.86      0.85     15150

In [10]:
from sklearn.naive_bayes import GaussianNB
# Initialize Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Fit the model to the training data
gnb.fit(X_train, y_train)

# Predict using the trained model on the test data
y_pred = gnb.predict(X_test)

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print('Confusion Matrix:')
print(cm)

# Compute classification report
report = classification_report(y_test, y_pred)

# Print classification report
print('Classification Report:')
print(report)

Confusion Matrix:
[[6436 1099]
 [5422 2193]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.54      0.85      0.66      7535
         1.0       0.67      0.29      0.40      7615

    accuracy                           0.57     15150
   macro avg       0.60      0.57      0.53     15150
weighted avg       0.60      0.57      0.53     15150

In [11]:
from sklearn.tree import DecisionTreeClassifier
# Initialize Decision Tree Classifier
dtc = DecisionTreeClassifier(criterion='entropy')

# Fit the model to the training data
dtc.fit(X_train, y_train)

# Predict using the trained model on the test data
y_pred = dtc.predict(X_test)

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print('Confusion Matrix:')
print(cm)

# Compute classification report
report = classification_report(y_test, y_pred)

# Print classification report
print('Classification Report:')
print(report)

Confusion Matrix:
[[6711  824]
 [ 592 7023]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.92      0.89      0.90      7535
         1.0       0.89      0.92      0.91      7615

    accuracy                           0.91     15150
   macro avg       0.91      0.91      0.91     15150
weighted avg       0.91      0.91      0.91     15150

In [12]:
from sklearn.ensemble import RandomForestClassifier
# Initialize RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion='entropy')

# Fit the model to the training data
rfc.fit(X_train, y_train)

# Predict using the trained model on the test data
y_pred = rfc.predict(X_test)

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print('Confusion Matrix:')
print(cm)

# Compute classification report
report = classification_report(y_test, y_pred)

# Print classification report
print('Classification Report:')
print(report)

Confusion Matrix:
[[7239  296]
 [ 432 7183]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      7535
         1.0       0.96      0.94      0.95      7615

    accuracy                           0.95     15150
   macro avg       0.95      0.95      0.95     15150
weighted avg       0.95      0.95      0.95     15150

In [16]:
# Assuming you have trained your models and stored them in a dictionary named `models`
models = {
    'SVC': svc,
    'KNN': knn,
    'GNB': gnb,
    'DTC': dtc,
    'RFC': rfc
}

from sklearn.metrics import classification_report

# Dictionary to store classification reports for each model
reports = {}

# Loop over the trained models
for model_name, model in models.items():
    # Predict using the trained model on the test data
    y_pred = model.predict(X_test)

    # Generate classification report
    report = classification_report(y_test, y_pred)

    # Store the classification report
    reports[model_name] = report

# Print classification reports
for model_name, report in reports.items():
    print(f"Classification Report for {model_name}:\n{report}\n")

Classification Report for SVC:
              precision    recall  f1-score   support

         0.0       0.79      0.83      0.81      7535
         1.0       0.83      0.78      0.80      7615

    accuracy                           0.81     15150
   macro avg       0.81      0.81      0.81     15150
weighted avg       0.81      0.81      0.81     15150


Classification Report for KNN:
              precision    recall  f1-score   support

         0.0       1.00      0.72      0.83      7535
         1.0       0.78      1.00      0.88      7615

    accuracy                           0.86     15150
   macro avg       0.89      0.86      0.85     15150
weighted avg       0.89      0.86      0.85     15150


Classification Report for GNB:
              precision    recall  f1-score   support

         0.0       0.54      0.85      0.66      7535
         1.0       0.67      0.29      0.40      7615

    accuracy                           0.57     15150
   macro avg       0.60      0.57      0.53     15150
weighted avg       0.60      0.57      0.53     15150


Classification Report for DTC:
              precision    recall  f1-score   support

         0.0       0.92      0.89      0.90      7535
         1.0       0.89      0.92      0.91      7615

    accuracy                           0.91     15150
   macro avg       0.91      0.91      0.91     15150
weighted avg       0.91      0.91      0.91     15150


Classification Report for RFC:
              precision    recall  f1-score   support

         0.0       0.94      0.96      0.95      7535
         1.0       0.96      0.94      0.95      7615

    accuracy                           0.95     15150
   macro avg       0.95      0.95      0.95     15150
weighted avg       0.95      0.95      0.95     15150

# Model Training and Evaluation

## we have trained five different models: Support Vector Classifier (SVC), K-Nearest Neighbors (KNN), Gaussian Naive Bayes (GNB), Decision Tree Classifier (DTC), and Random Forest Classifier (RFC).

## Each model has been evaluated using classification metrics such as precision, recall, F1-score, and accuracy.

## The classification reports provide a detailed evaluation of each model's performance on both classes (0 and 1) of the target variable 'FLAG'.

## From the classification reports, it appears that the Random Forest Classifier (RFC) has the highest overall performance with the highest accuracy and F1-scores for both classes.

# Overall Evaluation

## The project has followed a systematic approach to data preprocessing, model training, and evaluation.

## The models have been evaluated thoroughly using appropriate metrics, providing insights into their performance.

## It's important to consider the context of your problem and the specific requirements of your application when selecting the final model. While RFC performs well overall, other factors such as computational efficiency and interpretability may also influence the model selection.

## To further improve the evaluation, you may consider techniques such as cross-validation and hyperparameter tuning.

# yapay sinir aÄŸÄ±